/* global window */
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const previewUrl=process.env.PREVIEW_URL??'http://localhost:5173';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--enable-unsafe-webgpu','--use-angle=swiftshader','--enable-features=Vulkan']});
const page=await browser.newPage({viewport:{width:1000,height:900}});
page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
await page.goto(previewUrl);
try{await page.locator('#loading.hidden').waitFor({timeout:90000});}catch{console.log(await page.locator('#loading').innerText());}
await page.screenshot({path:'/tmp/droplet-desktop.png'});
console.log('title',await page.title(),'loaded',await page.locator('#loading').getAttribute('class'));
const snapshot=()=>page.evaluate(()=>window.dropletDebug);
const initial=await snapshot();assert(initial?.finite,'finite rendered body');
await page.mouse.move(500,350);await page.mouse.down();await page.mouse.move(600,210,{steps:12});
await page.waitForTimeout(200);const held=await snapshot();assert(held.grabs===1,'mouse grabs droplet');
assert(Math.hypot(...held.camera.map((v,i)=>v-initial.camera[i]))<.02,'camera stays near during grab');
await page.screenshot({path:'/tmp/droplet-stretch.png'});
await page.mouse.up();await page.waitForTimeout(700);
assert((await snapshot()).grabs===0,'release clears grab');
await page.getByRole('button',{name:'Reset Squish Crew'}).click();
const beforeOrbit=await snapshot();
await page.mouse.move(80,600);await page.mouse.down();await page.mouse.move(230,630,{steps:8});await page.mouse.up();
await page.waitForTimeout(200);const orbited=await snapshot();assert(orbited.finite);
assert(Math.hypot(...orbited.camera.map((v,i)=>v-beforeOrbit.camera[i]))>.001,'empty-floor drag orbits');
await page.getByRole('button',{name:'Mute sound'}).click();
assert(await page.getByRole('button',{name:'Enable sound'}).getAttribute('aria-pressed')==='true');
console.log('desktop interactions passed');
const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const phone=await mobile.newPage();await phone.goto(previewUrl);
await phone.locator('#loading.hidden').waitFor({timeout:90000});
await phone.screenshot({path:'/tmp/droplet-mobile.png'});
await phone.touchscreen.tap(195,410);await phone.waitForTimeout(300);
assert(await phone.evaluate(()=>window.dropletDebug.finite),'mobile tap remains finite');
await phone.getByRole('button',{name:'Reset Squish Crew'}).click();
const cdp=await mobile.newCDPSession(phone);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:195,y:350,id:1}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:230,y:260,id:1}]});
await phone.waitForTimeout(100);
assert(await phone.evaluate(()=>window.dropletDebug.grabs===1),'touch grabs body');
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await phone.waitForFunction(()=>window.dropletDebug.grabs===0,{},{timeout:10000});
await phone.getByRole('button',{name:'Reset Squish Crew'}).click();
const distance=()=>phone.evaluate(()=>Math.hypot(...window.dropletDebug.camera.map((v,i)=>v-window.dropletDebug.center[i])));
const beforePinch=await distance();
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:100,y:680,id:1},{x:290,y:680,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:65,y:680,id:1},{x:325,y:680,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await phone.waitForTimeout(150);assert(Math.abs(await distance()-beforePinch)>.001,'pinch changes camera distance');
await phone.setViewportSize({width:844,height:390});
await phone.waitForTimeout(150);await phone.screenshot({path:'/tmp/droplet-landscape.png'});
console.log('mobile touch load passed',await phone.evaluate(()=>window.dropletDebug.quality));
await browser.close();
